*** 
*** ReFox X  #UK933629  MANRIQUE ORELLANA  MANSOFT SYSTEMS [VFP80]
***
SET EXCLUSIVE OFF
SET MULTILOCKS ON
SET DEFAULT TO SYS(2003)
OPEN DATABASE &Clabase SHARED
ENDPROC
**
*** 
*** ReFox - retrace your steps ... 
***
