*** 
*** ReFox X  #UK933629  MANRIQUE ORELLANA  MANSOFT SYSTEMS [VFP80]
***
SET LIBRARY TO rawprint5.fll ADDITIVE
SET PRINTER TO FILE &ARCHIVO
SET CONSOLE OFF
SET DEVICE TO PRINTER
SET MARGIN TO 0
SET PRINTER ON
?? CHR(27) + '@' + CHR(27) + 'M' +  ;
   CHR(18)
SET PRINTER OFF
RETURN
ENDPROC
**
*** 
*** ReFox - retrace your steps ... 
***
