*!* EJEMPLO DE INTEGRACIÓN VFPsControlSkin
*!* By VFPSTEAM BI SOLUTIONS 

SET CONSOLE OFF
SET TALK OFF

*!* INICIAR VFPSCONTROLSKIN (REALIZARLO SIEMPRE DESDE SU MAIN PRINCIPAL)
*!* PARAMETROS
*!* APPLICATION = ENTORNO PRINCIPAL DE VISUAL FOXPRO
*!* _SCREEN     = OBJETO DONDE SE VA A CREAR VFPsControlSkin
*!* 1           = TIPOS DE SKIN VA DESDE 1 A 8

IF FILE("VFPsControlSkin.Exe")
   VFPsControlSkin(APPLICATION,_SCREEN,"5") && SE ENVIA EL STYLE OFFICE 2010 BLUE
ENDIF

*!* LLENAR PARAMETROS VFPS MESSAGEBOX
_SCREEN.llHyperLinks  = .T.                 &&COLOCAR EN .T. SI SE DESEA USAR HYPERLINKS.
_SCREEN.lcTituloText  = "Atención !!"       &&TITULO OPCIONAL QUE DESEAMOS VISUALIZAR ANTES DEL MENSAJE EN EL VFPS MESSAGEBOX
_SCREEN.lcFooterText  = "<A HREF=" + ["] + "http://www.vfpsteam.com" + ["] + ">VFPSTEAM BI " + ALLTRIM(STR(YEAR(DATE()))) + "</A> Todos los Derechos Reservados"
_SCREEN.llVista8      = .F.				    &&SI DESEA USAR EL ESTILO DE VFPS MESSAGEBOX DE WINDOWS 8 COLOCARLO EN .T.
_SCREEN.lnDialogWidth = 0					&&TAMAÑO DE LA VENTANA DE VFPS MESSAGEBOX

DO FORM frm_ejemplo